import {BarSummary,BarTrade} from './types';
import * as XLSX from 'xlsx';
const norm=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]/g,'');
const num=(v:unknown)=>{if(typeof v==='number')return v;let s=String(v??'').trim().replace(/,/g,'');if(!s)return null;let x=Number(s.replace('%',''));if(!Number.isFinite(x))return null;return /%$/.test(String(v).trim())?x/100:x;};
const key=(v:unknown)=>norm(String(v??''));
export function parse7bar(csv:string):{trades:BarTrade[];summary:BarSummary}{const wb=XLSX.read(csv,{type:'string'});const trades:BarTrade[]=[];let summary:BarSummary={bookedPct:null,runningPct:null};for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sn],{header:1,defval:''});for(let i=0;i<rows.length;i++){const row=rows[i];const vals=row.map(v=>String(v??'').trim());const joined=vals.map(key).join('|');if(joined.includes('7barbooked')||joined.includes('7barrunning')){const next=rows[i+1]||[];for(let c=0;c<row.length;c++){const label=key(row[c]);if(label.includes('7barbooked'))summary.bookedPct=num(next[c]);if(label.includes('7barrunning'))summary.runningPct=num(next[c]);}for(const v of row){const ss=String(v??'').trim();if(/^-?\d+(\.\d+)?%$/.test(ss)){const x=num(ss);if(joined.includes('7barbooked')&&summary.bookedPct==null)summary.bookedPct=x;if(joined.includes('7barrunning')&&summary.runningPct==null)summary.runningPct=x;}}}
 const headers=vals.map(key);if(headers.includes('ticker')&&headers.includes('tradestatus')){const idx=(names:string[])=>{for(const name of names){const j=headers.indexOf(key(name));if(j>=0)return j}return -1};const ti=idx(['Ticker']),si=idx(['Trade Status','Status']),ci=idx(['CMP','Current Price']),bi=idx(['Buy Price','Buy']),ta=idx(['Target']),st=idx(['Stoploss','Stop Loss']),pp=idx(['Position %','Position']),bp=idx(['Booked PF','Booked']),rp=idx(['Running PF','Running']),ni=idx(['Remarks','Notes']);for(let j=i+1;j<rows.length;j++){const r=rows[j];const ticker=String(r[ti]??'').trim();if(!ticker||/^closed trades$/i.test(ticker)||/^active trades$/i.test(ticker))break;const status=String(r[si]??'').trim();if(!status)continue;trades.push({ticker,status,cmp:num(r[ci]),buy:num(r[bi]),target:num(r[ta]),stop:num(r[st]),positionPct:num(r[pp]),bookedPct:num(r[bp]),runningPct:num(r[rp]),notes:String(r[ni]??'').trim()});} }
 } }
 const m=new Map<string,BarTrade>();for(const t of trades)m.set(t.ticker.toUpperCase(),t);return {trades:[...m.values()],summary};}
